{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ikonic.serviceAccountName" . }}
  labels:
{{ include "ikonic.labels" . | indent 4 }}
{{- end -}}

